// mockup/ts/data-events.ts
import type { MockEvent, MockExam, MockStaff, MockRoom } from "./data-types";

export const MOCK_EVENTS: MockEvent[] = [
    {
        id: "ev-1",
        title: "Modellierung & Programmierung 1",
        courseId: "c-1",
        date: "2026-10-12",
        day: "Mo",
        startHour: 9,
        durationHours: 2,
        time: "09:15 – 10:45",
        room: "Felix-Klein-Hörsaal",
        building: "Paulinum",
        instructor: "Prof. Dr. Martin Bogdan",
        type: "Veranstaltung",
    },
    {
        id: "ev-2",
        title: "Modellierung & Prog. Übung",
        courseId: "c-2",
        date: "2026-10-13",
        day: "Di",
        startHour: 11,
        durationHours: 2,
        time: "11:15 – 12:45",
        room: "SG 3-10",
        building: "Seminargebäude",
        instructor: "M.Sc. Tobias Schmidt",
        type: "Veranstaltung",
    },
    {
        id: "ev-3",
        title: "Algorithmen & Datenstrukturen 1",
        courseId: "c-3",
        date: "2026-10-14",
        day: "Mi",
        startHour: 13,
        durationHours: 2,
        time: "13:15 – 14:45",
        room: "Audimax",
        building: "Neues Augusteum",
        instructor: "Prof. Dr. Erhard Rahm",
        type: "Veranstaltung",
    },
    {
        id: "ev-4",
        title: "Algo & Datenstrukturen Übung",
        courseId: "c-4",
        date: "2026-10-15",
        day: "Do",
        startHour: 9,
        durationHours: 2,
        time: "09:15 – 10:45",
        room: "SG 2-14",
        building: "Seminargebäude",
        instructor: "Dr. Anna Meißner",
        type: "Veranstaltung",
    },
    {
        id: "ev-5",
        title: "Datenbanksysteme 1",
        courseId: "c-5",
        date: "2026-10-16",
        day: "Fr",
        startHour: 11,
        durationHours: 2,
        time: "11:15 – 12:45",
        room: "Felix-Klein-Hörsaal",
        building: "Paulinum",
        instructor: "Prof. Dr. Erhard Rahm",
        type: "Veranstaltung",
    },
];

export const MOCK_EXAMS: MockExam[] = [
    {
        id: "ex-1",
        code: "10-201-2001-P01",
        name: "Klausur Modellierung und Programmierung 1",
        moduleId: "mod-1",
        date: "16.02.2027",
        time: "09:00 – 11:00",
        room: "Audimax",
        examiner: "Prof. Dr. Martin Bogdan",
        type: "Klausur",
        mandatory: true,
    },
    {
        id: "ex-2",
        code: "10-201-2011-P01",
        name: "Klausur Algorithmen und Datenstrukturen 1",
        moduleId: "mod-2",
        date: "23.02.2027",
        time: "14:00 – 16:00",
        room: "Audimax",
        examiner: "Prof. Dr. Erhard Rahm",
        type: "Klausur",
        mandatory: true,
    },
    {
        id: "ex-3",
        code: "10-202-2301-P01",
        name: "Klausur Datenbanksysteme 1",
        moduleId: "mod-5",
        date: "02.03.2027",
        time: "10:00 – 12:00",
        room: "Felix-Klein-Hörsaal",
        examiner: "Prof. Dr. Erhard Rahm",
        type: "Klausur",
        mandatory: true,
    },
];

export const MOCK_STAFF: MockStaff[] = [
    {
        id: "st-1",
        name: "Prof. Dr. Erhard Rahm",
        title: "Lehrstuhl für Datenbanken",
        faculty: "Fakultät für Mathematik und Informatik",
        coursesCount: 4,
        examsCount: 3,
        email: "rahm@informatik.uni-leipzig.de",
        office: "Neues Augusteum, A-412",
    },
    {
        id: "st-2",
        name: "Prof. Dr. Martin Bogdan",
        title: "Angewandte Informatik",
        faculty: "Fakultät für Mathematik und Informatik",
        coursesCount: 3,
        examsCount: 2,
        email: "bogdan@informatik.uni-leipzig.de",
        office: "Neues Augusteum, B-320",
    },
    {
        id: "st-3",
        name: "Dr. Anna Meißner",
        title: "Wissenschaftliche Mitarbeiterin",
        faculty: "Fakultät für Mathematik und Informatik",
        coursesCount: 2,
        examsCount: 1,
        email: "meissner@informatik.uni-leipzig.de",
        office: "Seminargebäude 3-14",
    },
];

export const MOCK_ROOMS: MockRoom[] = [
    {
        id: "rm-1",
        name: "Audimax",
        building: "Neues Augusteum, Augustusplatz 10",
        capacity: 800,
        type: "Hörsaal",
        accessible: true,
    },
    {
        id: "rm-2",
        name: "Felix-Klein-Hörsaal",
        building: "Paulinum, Augustusplatz 10",
        capacity: 350,
        type: "Hörsaal",
        accessible: true,
    },
    {
        id: "rm-3",
        name: "SG 3-10",
        building: "Seminargebäude, Universitätsstraße 1",
        capacity: 45,
        type: "Seminarraum",
        accessible: true,
    },
    {
        id: "rm-4",
        name: "Rechnerpool 1",
        building: "Neues Augusteum, A-110",
        capacity: 30,
        type: "Rechnerpool",
        accessible: false,
    },
];
