// mockup/ts/data.ts
import type { MockModule } from "./data-types";
export * from "./data-types";
export * from "./data-courses";
export * from "./data-events";

export const MOCK_MODULES: MockModule[] = [
    {
        id: "mod-1",
        code: "10-201-2001",
        name: "Modellierung und Programmierung 1",
        lp: 10,
        sws: 6,
        semester: "WiSe 2025/26",
        faculty: "Fakultät für Mathematik und Informatik",
        language: "Deutsch",
        description: "Einführung in funktionale und objektorientierte Programmierung, Entwurfsmuster und Datenstrukturen.",
        responsible: "Prof. Dr. Martin Bogdan",
        coursesCount: 3,
        examsCount: 1,
    },
    {
        id: "mod-2",
        code: "10-201-2011",
        name: "Algorithmen und Datenstrukturen 1",
        lp: 5,
        sws: 4,
        semester: "WiSe 2025/26",
        faculty: "Fakultät für Mathematik und Informatik",
        language: "Deutsch",
        description: "Entwurfsprinzipien für Algorithmen: Divide & Conquer, Dynamische Programmierung, Graph-Algorithmen.",
        responsible: "Prof. Dr. Erhard Rahm",
        coursesCount: 2,
        examsCount: 1,
    },
    {
        id: "mod-3",
        code: "10-201-2007",
        name: "Wahrscheinlichkeitstheorie und Statistik",
        lp: 5,
        sws: 4,
        semester: "WiSe 2025/26",
        faculty: "Fakultät für Mathematik und Informatik",
        language: "Deutsch",
        description: "Kombinatorik, diskrete und stetige Zufallsvariablen, Gesetz der großen Zahlen, Testtheorie.",
        responsible: "Prof. Dr. Bernd Kirchheim",
        coursesCount: 2,
        examsCount: 1,
    },
    {
        id: "mod-4",
        code: "09-101-1102",
        name: "Einführung in die Wirtschaftswissenschaften",
        lp: 10,
        sws: 4,
        semester: "WiSe 2025/26",
        faculty: "Wirtschaftswissenschaftliche Fakultät",
        language: "Deutsch",
        description: "Mikroökonomische Grundlagen, Preisbildung auf Märkten, Konsumenten- und Unternehmenstheorie.",
        responsible: "Prof. Dr. Thomas Lenk",
        coursesCount: 2,
        examsCount: 1,
    },
    {
        id: "mod-5",
        code: "10-202-2301",
        name: "Datenbanksysteme 1",
        lp: 5,
        sws: 3,
        semester: "WiSe 2025/26",
        faculty: "Fakultät für Mathematik und Informatik",
        language: "Deutsch",
        description: "Relationales Datenmodell, SQL, Normalformen, physische Datenorganisation und Transaktionen.",
        responsible: "Prof. Dr. Erhard Rahm",
        coursesCount: 2,
        examsCount: 1,
    },
    {
        id: "mod-6",
        code: "11-001-0101",
        name: "Kognitive Psychologie",
        lp: 5,
        sws: 3,
        semester: "WiSe 2025/26",
        faculty: "Fakultät für Lebenswissenschaften",
        language: "Deutsch",
        description: "Wahrnehmung, Aufmerksamkeit, Gedächtnismodelle und kognitive Informationsverarbeitung.",
        responsible: "Prof. Dr. Erich Schröger",
        coursesCount: 2,
        examsCount: 1,
    },
];
