// mockup/ts/data-courses.ts
import type { MockCourse } from "./data-types";

export const MOCK_COURSES: MockCourse[] = [
    {
        id: "c-1",
        code: "10-201-2001-V01",
        name: "Modellierung und Programmierung 1 (Vorlesung)",
        moduleId: "mod-1",
        moduleName: "Modellierung und Programmierung 1",
        type: "Vorlesung",
        day: "Mo",
        time: "09:15 – 10:45",
        room: "Felix-Klein-Hörsaal",
        instructor: "Prof. Dr. Martin Bogdan",
        sws: 4,
    },
    {
        id: "c-2",
        code: "10-201-2001-U01",
        name: "Modellierung und Programmierung 1 (Übung Gr. 1)",
        moduleId: "mod-1",
        moduleName: "Modellierung und Programmierung 1",
        type: "Übung",
        day: "Di",
        time: "11:15 – 12:45",
        room: "SG 3-10",
        instructor: "M.Sc. Tobias Schmidt",
        sws: 2,
    },
    {
        id: "c-3",
        code: "10-201-2011-V01",
        name: "Algorithmen und Datenstrukturen 1 (Vorlesung)",
        moduleId: "mod-2",
        moduleName: "Algorithmen und Datenstrukturen 1",
        type: "Vorlesung",
        day: "Mi",
        time: "13:15 – 14:45",
        room: "Audimax (Neues Augusteum)",
        instructor: "Prof. Dr. Erhard Rahm",
        sws: 2,
    },
    {
        id: "c-4",
        code: "10-201-2011-U01",
        name: "Algorithmen und Datenstrukturen 1 (Übung Gr. 2)",
        moduleId: "mod-2",
        moduleName: "Algorithmen und Datenstrukturen 1",
        type: "Übung",
        day: "Do",
        time: "09:15 – 10:45",
        room: "SG 2-14",
        instructor: "Dr. Anna Meißner",
        sws: 2,
    },
    {
        id: "c-5",
        code: "10-202-2301-V01",
        name: "Datenbanksysteme 1 (Vorlesung)",
        moduleId: "mod-5",
        moduleName: "Datenbanksysteme 1",
        type: "Vorlesung",
        day: "Fr",
        time: "11:15 – 12:45",
        room: "Felix-Klein-Hörsaal",
        instructor: "Prof. Dr. Erhard Rahm",
        sws: 2,
    },
];
